# fly.toml app configuration file generated for moodify on 2024-10-06T02:54:35-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'moodify'
primary_region = 'lax'

[build]

[env]
  PORT = "3000"
  CLIENT_URL = "https://moodify.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
